### PR TITLE
Collect groups, login password for MQTT, new config options

### PR DESCRIPTION
**Pull request by dgomes**
Hi! 

Would love to merge your changes back to dali2mqtt if your interested

### CODE REVIEW

**Comment by AdamN1** [comment]
@dgomes can you resolve conflict and merge this?

**Comment by dgomes** [comment]
Sure, the only issue is with requirements.txt

I already asked for a 0.7.1 that addresses hasseb imports missing in 0.7. As soon as that package is published the requirements.txt can be fixed to a working version and I can merge the forks

**Comment by AdamN1** [comment]
Can I help you somehow?
Do you have a list of features to implement?

**Comment by dgomes** [comment]
I only have 4 DALI lamps... I'm personally OK with the current features, but keen in supporting this project.

What features would you have in mind ?

**Comment by AdamN1** [comment]
> What features would you have in mind ?

At the moment I'm connecting lamps do DALI bus. When I connect a new device, scan bus via DALI_bus.initialize_bus() the addressing of the others changes. The result is the need to remap the lamps in HA to room names.

Maybe there is other way to map DALI device to HA that by DALI address?

**Comment by dgomes** [comment]
Please create a new issue with feature requests, so we don't clutter this issue

**Pull request closed without merging**
