### PR TITLE
Added configuration for dali bus size, scan for more lamps

### PR DESCRIPTION
**Pull request by kbacia7**
Hello, I added in configuration file and as argument to script option `--dali-bus-size` (#17) which inform about maximum number of lamps connected to dali bus.

I changed `dali_scan` function to scan by `--dali-bus-size` (default is 64), also I added a small information about initialized lamps (not only when DEBUG is turned on) to inform user about worked lamps

### CODE REVIEW

**Comment by dgomes** [comment]
your dali-bus-size is the same as max_lamp... 

I accept my name (max_lamp) might not be the best, but dali-bus-size is equally not that good.

What about **devices to scan** ? 

I created this because it was taking too long to scan the full bus when it had already detected all my lamps.

**Comment by kbacia7** [comment]
Ok, maybe we can change a bit scanning and when found, initialize lamp without waiting to end of scanning? 
Thanks to this we can scan for all devices without long waiting to initialisation

**Comment by dgomes** [comment]
Thats what it currently does, if you have 4 lamps when the 4th (max_lamps) is found you exit the scan procedure.

**Comment by kbacia7** [comment]
Yes, but idea is to scan for all available devices, if I correct understand, bus can have 64 devices and we don't want end scanning after reaching 4? 
I think that during scan we can initialise lamps and scan for all devices

**Comment by dgomes** [comment]
it max_lamps=64 it will scan the 64 devices... 

but if I have 4 physical devices (which I'm aware of) then there is no point in continuing the search after I have found those 4 devices.

Look, this code is used AFTER you have commissioned your DALI random addresses to Short addresses, at this stage there is no point in searching addresses you already know there are no devices there.

What dali2mqtt misses is a function/procedure to commission devices (I did this using the HASSEB application, as this is done only once in a lifetime)

**Comment by kbacia7** [comment]
Changed in #27

**Pull request closed without merging**
